const $=id=>document.getElementById(id);const fmt=n=>Number(n).toFixed(2);
const STORE='golddesk.v5',ACC='golddesk.acc',DONE='golddesk.liqdone';
const loadS=()=>{try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch(e){return{}}};
const saveS=s=>localStorage.setItem(STORE,JSON.stringify(s));
const cairoDay=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Africa/Cairo'});
const GOLD_NEWS=/fomc|fed|powell|interest rate|cpi|ppi|pce|nfp|nonfarm|unemployment|payroll|gdp|inflation|treasury|dollar|dxy|gold|xau|yield/i;
document.querySelectorAll('.acc>button').forEach(btn=>{const acc=btn.parentElement;const saved=JSON.parse(localStorage.getItem(ACC)||'{}');if(saved[acc.dataset.acc]===false)acc.classList.add('closed');btn.onclick=()=>{acc.classList.toggle('closed');const st=JSON.parse(localStorage.getItem(ACC)||'{}');st[acc.dataset.acc]=!acc.classList.contains('closed');localStorage.setItem(ACC,JSON.stringify(st));};});
function loadDone(){try{const o=JSON.parse(localStorage.getItem(DONE)||'{}');if(o.day!==cairoDay())return{day:cairoDay(),ids:{}};return o}catch(e){return{day:cairoDay(),ids:{}}}}
function saveDone(o){o.day=cairoDay();localStorage.setItem(DONE,JSON.stringify(o))}
function isDone(id){return!!loadDone().ids[id]}
function setDone(id,v){const o=loadDone();if(v)o.ids[id]={at:Date.now()};else delete o.ids[id];saveDone(o)}
function num(v){const n=parseFloat(v);return Number.isFinite(n)?n:null}
function goldEvents(events){const seen=new Set(),out=[];for(const e of events||[]){const name=e.name||'';const usd=e.currency==='USD'||e.countryCode==='US';if(!(usd&&GOLD_NEWS.test(name)))continue;const k=name+e.time;if(seen.has(k))continue;seen.add(k);out.push(e)}return out.sort((a,b)=>new Date(a.time)-new Date(b.time))}
function newsBias(events){let score=0;const notes=[];const now=Date.now();for(const e of events){const name=(e.name||'').toLowerCase();if(now-new Date(e.time).getTime()>36*3600*1000)continue;const act=num(e.actual),fc=num(e.forecast),prev=num(e.previous);let local=0,why='';if(/interest rate|fed|fomc/.test(name)&&act!=null&&prev!=null){if(act>prev){local-=2;why=e.name+' hiked'}else if(act<prev){local+=2;why=e.name+' cut'}else{local-=0.4;why=e.name+' held'}}else if(/cpi|ppi|pce|inflation|nfp/.test(name)&&act!=null&&fc!=null){if(act>fc)local-=1;else if(act<fc)local+=1;why=e.name}if(why){score+=local;notes.push(why)}}return{dir:score<=-1?'sell':score>=1?'buy':'neutral',label:'News bias: '+(score<=-1?'SELL':score>=1?'BUY':'mixed'),notes}}
function momentum(q,s){const mid=q.mid||q.bid;const rng=Math.max((s.dayHigh||mid)-(s.dayLow||mid),1);const chg=q.dayDiffPercent||0;let dir='neutral',label='Momentum mixed';if(chg<=-0.25){dir='sell';label='Sell momentum'}else if(chg>=0.25){dir='buy';label='Buy momentum'}return{dir:dir,label:label,chg:chg}}
function initState(q){const s=loadS();const day=cairoDay();if(s.day&&s.day!==day){s.pdh=s.dayHigh;s.pdl=s.dayLow;s.alerted={};s.touched={}}s.day=day;s.dayHigh=Math.max(s.dayHigh||0,q.high||q.mid);s.dayLow=Math.min(s.dayLow||1e9,q.low||q.mid);if(!s.pdh)s.pdh=q.high;if(!s.pdl)s.pdl=q.low;s.londonHigh=Math.max(s.londonHigh||q.high,q.high);s.londonLow=Math.min(s.londonLow||q.low,q.low);s.nyHigh=Math.max(s.nyHigh||q.high,q.high);s.nyLow=Math.min(s.nyLow||q.low,q.low);saveS(s);return s}
function zoneList(s){return[{id:'pdh',kind:'bsl',name:'PDH',from:s.pdh-2.5,to:s.pdh+1.5},{id:'pdl',kind:'ssl',name:'PDL',from:s.pdl-1.5,to:s.pdl+2.5},{id:'tdh',kind:'bsl',name:'Today high',from:s.dayHigh-3,to:s.dayHigh+1.2},{id:'tdl',kind:'ssl',name:'Today low',from:s.dayLow-1.2,to:s.dayLow+3}]}
function isDone(id){try{const o=JSON.parse(localStorage.getItem(DONE)||'{}');return o.day===cairoDay()&&o.ids&&o.ids[id]}catch(e){return false}}
function setDone(id,v){let o={day:cairoDay(),ids:{}};try{o=JSON.parse(localStorage.getItem(DONE)||'{}');if(o.day!==cairoDay())o={day:cairoDay(),ids:{}}}catch(e){o={day:cairoDay(),ids:{}}}if(v)o.ids[id]={at:Date.now()};else delete o.ids[id];localStorage.setItem(DONE,JSON.stringify(o))}
function parseBars(raw){return (raw&&raw.bars||[]).filter(b=>!b.isOpen).map(b=>({o:+b.open,h:+b.high,l:+b.low,c:+b.close})).reverse()}
function withTimeout(p,ms){return Promise.race([p,new Promise(function(_,rej){setTimeout(function(){rej(new Error('t'))},ms)})])}
async function ohlc(interval,limit){const r=await withTimeout(fetch('https://biquote.io/api/XAUUSD/ohlc?interval='+interval+'&limit='+limit),8000);if(!r.ok)throw new Error(interval);return parseBars(await r.json())}
function swings(bars,L){L=L||2;const out=[];for(let i=L;i<bars.length-L;i++){const w=bars.slice(i-L,i+L+1);if(bars[i].h===Math.max.apply(null,w.map(x=>x.h)))out.push({t:'h',p:bars[i].h});if(bars[i].l===Math.min.apply(null,w.map(x=>x.l)))out.push({t:'l',p:bars[i].l})}return out}
function lastOf(sw,t){for(let i=sw.length-1;i>=0;i--)if(sw[i].t===t)return sw[i];return null}
function structure(bars){const sw=swings(bars,2);const hs=sw.filter(x=>x.t==='h').slice(-3);const ls=sw.filter(x=>x.t==='l').slice(-3);let tag='Range / Neutral';if(hs.length>=2&&ls.length>=2){const hh=hs[hs.length-1].p>hs[hs.length-2].p,hl=ls[ls.length-1].p>ls[ls.length-2].p,lh=hs[hs.length-1].p<hs[hs.length-2].p,ll=ls[ls.length-1].p<ls[ls.length-2].p;if(hh&&hl)tag='Bullish HH/HL';else if(lh&&ll)tag='Bearish LH/LL'}const lastH=lastOf(sw,'h'),lastL=lastOf(sw,'l'),last=bars[bars.length-1];let event='None',bias='Neutral';if(lastH&&last.c>lastH.p){event='Bullish BOS';bias='Bullish'}if(lastL&&last.c<lastL.p){event='Bearish BOS';bias='Bearish'}if(tag.indexOf('Bullish')===0&&bias==='Neutral')bias='Bullish';if(tag.indexOf('Bearish')===0&&bias==='Neutral')bias='Bearish';return{sw:sw,tag:tag,event:event,bias:bias,lastH:lastH,lastL:lastL,hi:Math.max.apply(null,bars.slice(-40).map(b=>b.h)),lo:Math.min.apply(null,bars.slice(-40).map(b=>b.l))}}
function fvgs(bars){const out=[];if(!bars||bars.length<3)return out;for(let i=2;i<bars.length;i++){const a=bars[i-2],c=bars[i];if(c.l>a.h)out.push({dir:'bull',low:a.h,high:c.l});if(c.h<a.l)out.push({dir:'bear',low:c.h,high:a.l})}return out.slice(-5)}
function lastFvg(list,dir){for(let i=list.length-1;i>=0;i--)if(list[i].dir===dir)return list[i];return null}
function displacement(bars){if(!bars||bars.length<8)return{yes:false,dir:'none'};const bodies=bars.slice(-12,-1).map(b=>Math.abs(b.c-b.o));const avg=bodies.reduce((a,b)=>a+b,0)/Math.max(bodies.length,1);const last=bars[bars.length-1];return{yes:Math.abs(last.c-last.o)>=avg*1.7,dir:last.c>last.o?'bull':'bear'}}
function hourKey(){return new Date().toLocaleString('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false})}
function loadHourPlan(){try{return JSON.parse(localStorage.getItem('golddesk.hourPlan')||'null')}catch(e){return null}}
function saveHourPlan(p){localStorage.setItem('golddesk.hourPlan',JSON.stringify(p))}
function cluster(levels,tol){tol=tol||8;const a=levels.filter(Boolean).sort(function(x,y){return x-y});if(!a.length)return null;const g=[];let cur=[a[0]];for(let i=1;i<a.length;i++){if(a[i]-cur[cur.length-1]<=tol)cur.push(a[i]);else{g.push(cur);cur=[a[i]]}}g.push(cur);g.sort(function(x,y){return y.length-x.length});return{lo:g[0][0],hi:g[0][g[0].length-1]}}
function buildHourlyZones(q,s,h1,m15,m5){const mid=q.mid||q.bid;const H1=h1&&h1.length>=20?structure(h1):null;const M15=m15&&m15.length>=20?structure(m15):null;const M5=m5&&m5.length>=10?structure(m5):null;const d5=displacement(m5||[]);const f5=fvgs(m5||[]);const b5=lastFvg(f5,'bull');const s5=lastFvg(f5,'bear');const rangeLo=Math.min.apply(null,[s.pdl,s.dayLow,H1&&H1.lo,mid-40].filter(Boolean));const rangeHi=Math.max.apply(null,[s.pdh,s.dayHigh,H1&&H1.hi,mid+40].filter(Boolean));const eq=rangeLo+(rangeHi-rangeLo)/2;const buy1={lo:rangeLo+2,hi:rangeLo+12};const sell1={lo:rangeHi-12,hi:rangeHi-2};const m5buy=b5?{lo:b5.low,hi:b5.high}:{lo:(M5&&M5.lastL?M5.lastL.p:mid-8),hi:(M5&&M5.lastL?M5.lastL.p+5:mid-3)};const m5sell=s5?{lo:s5.low,hi:s5.high}:{lo:(M5&&M5.lastH?M5.lastH.p-5:mid+3),hi:(M5&&M5.lastH?M5.lastH.p:mid+8)};return{key:hourKey(),h1tag:H1?H1.tag:'n/a',m15tag:M15?M15.tag:'n/a',m5tag:M5?M5.tag+' | disp '+(d5.yes?d5.dir:'no'):'n/a',m5disp:d5.yes?d5.dir:'no',eq:+eq.toFixed(1),rangeLo:+rangeLo.toFixed(1),rangeHi:+rangeHi.toFixed(1),invBuy:+(rangeLo-8).toFixed(1),noBuyAbove:+(eq+8).toFixed(1),noSellBelow:+(eq-8).toFixed(1),zones:[{name:'Primary buy',side:'buy',lo:+buy1.lo.toFixed(1),hi:+buy1.hi.toFixed(1),sl:+(buy1.lo-8).toFixed(1),t1:+(buy1.hi+22).toFixed(1),t2:+(buy1.hi+38).toFixed(1)},{name:'Primary sell',side:'sell',lo:+sell1.lo.toFixed(1),hi:+sell1.hi.toFixed(1),sl:+(sell1.hi+8).toFixed(1),t1:+(sell1.lo-22).toFixed(1),t2:+(sell1.lo-38).toFixed(1)},{name:'M5 buy',side:'buy',lo:+Math.min(m5buy.lo,m5buy.hi).toFixed(1),hi:+Math.max(m5buy.lo,m5buy.hi).toFixed(1),sl:+(Math.min(m5buy.lo,m5buy.hi)-4).toFixed(1),t1:+(Math.max(m5buy.lo,m5buy.hi)+10).toFixed(1),t2:+(Math.max(m5buy.lo,m5buy.hi)+20).toFixed(1)},{name:'M5 sell',side:'sell',lo:+Math.min(m5sell.lo,m5sell.hi).toFixed(1),hi:+Math.max(m5sell.lo,m5sell.hi).toFixed(1),sl:+(Math.max(m5sell.lo,m5sell.hi)+4).toFixed(1),t1:+(Math.min(m5sell.lo,m5sell.hi)-10).toFixed(1),t2:+(Math.min(m5sell.lo,m5sell.hi)-20).toFixed(1)}]}}
function deskPlan(q,s,h1,m15,m5){const mid=q.mid||q.bid;let pack=loadHourPlan();if(!pack||pack.key!==hourKey()||!pack.zones){pack=buildHourlyZones(q,s,h1,m15,m5);saveHourPlan(pack)}function st(z){if(z.side==='buy'&&mid<pack.invBuy)return['blocked','Cancelled - demand break'];if(z.side==='buy'&&mid>pack.noBuyAbove)return['blocked','No scalp longs above equilibrium'];if(z.side==='sell'&&mid<pack.noSellBelow)return['pending','Do not sell cheap without rejection'];if(mid>=z.lo&&mid<=z.hi)return['avail','In zone - wait M5 rejection'];if(z.side==='buy'&&mid>z.hi)return['pending','Wait for pullback into zone'];if(z.side==='sell'&&mid<z.lo)return['pending','Wait for rally into zone'];return['pending','Watch']}const cards=pack.zones.map(function(z){const ss=st(z);const entry=(z.lo+z.hi)/2;return Object.assign({},z,{status:ss[0],label:ss[1],rr:(Math.abs(z.t1-entry)/Math.max(Math.abs(entry-z.sl),0.5)).toFixed(1)})});let dir='NO TRADE',entry='-',sl='-',t1='-',t2='-',rr='-';let best='Hourly M5 map active. Do not chase mid-range around '+fmt(pack.eq)+'.';let play='Wait for M5 tap + rejection.';const hit=cards.find(function(c){return c.status==='avail'});if(hit){dir=hit.side==='buy'?'BUY':'SELL';entry=fmt(hit.lo)+'-'+fmt(hit.hi);sl=fmt(hit.sl);t1=fmt(hit.t1);t2=fmt(hit.t2);rr='1:'+hit.rr;best='Price is inside '+hit.name+'.';play=(dir==='BUY'?'Buy':'Sell')+' after M5 rejection.'}return{verdict:dir==='BUY'||dir==='SELL'?dir+' - M5 trigger':'NO TRADE - wait for zone',trade:dir==='BUY'||dir==='SELL',rows:[['Plan hour',pack.key+' Cairo'],['H1 / M15 / M5',(pack.h1tag||'-')+' / '+(pack.m15tag||'-')+' / '+(pack.m5tag||'-')],['M5 displacement',pack.m5disp||'no'],['Now',fmt(mid)],['Equilibrium',fmt(pack.eq)],['Best scenario',best],['Play',play],['Bias',dir],['Entry',entry],['Stop',sl],['TP1 / TP2',t1+' / '+t2],['R:R',rr]],cards:cards}}
function advancedTA(q,s,h4,h1,m15,m5){const mid=q.mid||q.bid;const H4=h4&&h4.length>=20?structure(h4):null;const H1=h1&&h1.length>=20?structure(h1):null;const M15=m15&&m15.length>=20?structure(m15):null;const M5=m5&&m5.length>=10?structure(m5):null;const d15=displacement(m15||[]);const d5=displacement(m5||[]);const f5=fvgs(m5||[]);const bull5=lastFvg(f5,'bull'),bear5=lastFvg(f5,'bear');const rngLo=Math.min(s.pdl||mid,s.dayLow||mid,H1&&H1.lo||mid);const rngHi=Math.max(s.pdh||mid,s.dayHigh||mid,H1&&H1.hi||mid);const eq=rngLo+(rngHi-rngLo)/2;return{rows:[['H4',H4?H4.bias+' | '+H4.event:'no data'],['H1',H1?H1.tag+' | '+H1.event:'no data'],['M15',M15?M15.tag+' | '+M15.event:'no data'],['M5',M5?M5.tag+' | '+M5.event:'no data'],['M15 displacement',d15.yes?('Yes '+d15.dir):'No'],['M5 displacement',d5.yes?('Yes '+d5.dir):'No'],['M5 Bull FVG',bull5?fmt(bull5.low)+'-'+fmt(bull5.high):'none'],['M5 Bear FVG',bear5?fmt(bear5.low)+'-'+fmt(bear5.high):'none'],['Premium / Discount',mid>=eq?'Premium':'Discount'],['PDH / PDL',fmt(s.pdh)+' / '+fmt(s.pdl)]]}}
function render(q,events,s,pack){const mid=q.mid||q.bid;const prev=mid/(1+(q.dayDiffPercent||0)/100);const diff=mid-prev;$('price').textContent=fmt(mid);$('price').className='price '+(diff>=0?'up':'down');$('chg').textContent=(diff>=0?'+':'')+fmt(diff)+' ('+(q.dayDiffPercent||0).toFixed(2)+'%)';$('hl').textContent='H '+fmt(q.high)+' L '+fmt(q.low);$('zones').innerHTML=zoneList(s).map(function(z){const d=isDone(z.id);return '<div class="zone'+(d?' done':'')+'"><div class="row"><label><input class="chk" type="checkbox" data-id="'+z.id+'" '+(d?'checked':'')+'/> <span class="tag '+z.kind+'">'+z.kind.toUpperCase()+'</span></label><span class="v">'+fmt(z.from)+' - '+fmt(z.to)+'</span></div><div>'+z.name+'</div></div>'}).join('');document.querySelectorAll('#zones input').forEach(function(el){el.onchange=function(){setDone(el.dataset.id,el.checked)}});const g=goldEvents(events);const nb=newsBias(g);const moS=momentum(q,s);$('news').innerHTML=g.length?g.slice().reverse().map(function(e){const t=new Date(e.time).toLocaleString('en-GB',{timeZone:'Africa/Cairo',hour:'2-digit',minute:'2-digit',weekday:'short'});return '<div class="news-item"><div class="row"><span class="tag bsl">USD</span><span class="meta">'+t+'</span></div><div>'+e.name+'</div></div>'}).join(''):'<div class="note">No high-impact events.</div>';const ta=advancedTA(q,s,pack&&pack.h4,pack&&pack.h1,pack&&pack.m15,pack&&pack.m5);$('analysis').innerHTML='<div class="row"><span class="k">Momentum</span><span class="v">'+moS.label+'</span></div><div class="row"><span class="k">News</span><span class="v">'+nb.label+'</span></div>'+ta.rows.map(function(r){return '<div class="row"><span class="k">'+r[0]+'</span><span class="v">'+r[1]+'</span></div>'}).join('');const desk=deskPlan(q,s,pack&&pack.h1,pack&&pack.m15,pack&&pack.m5);$('plan').innerHTML='<div class="verdict '+(desk.trade?'avail':'pending')+'">'+desk.verdict+'</div>'+desk.rows.map(function(r){return '<div class="row"><span class="k">'+r[0]+'</span><span class="v">'+r[1]+'</span></div>'}).join('')+desk.cards.map(function(c){return '<div class="news-item"><div class="row"><strong>'+c.name+'</strong><span class="badge '+c.status+'">'+c.label+'</span></div><div class="row"><span class="k">Zone</span><span class="v">'+fmt(c.lo)+'-'+fmt(c.hi)+'</span></div><div class="row"><span class="k">SL / TP1 / TP2</span><span class="v">'+fmt(c.sl)+' / '+fmt(c.t1)+' / '+fmt(c.t2)+'</span></div></div>'}).join('');if($('live'))$('live').innerHTML='<div class="verdict '+(desk.trade?'avail':'pending')+'">'+desk.verdict+'</div>'+desk.cards.map(function(c){return '<div class="news-item"><div class="row"><strong>'+c.name+'</strong><span class="badge '+c.status+'">'+c.label+'</span></div><div class="row"><span class="k">Zone</span><span class="v">'+fmt(c.lo)+'-'+fmt(c.hi)+'</span></div></div>'}).join('');}
async function refresh(){try{const qr=await withTimeout(fetch('https://biquote.io/api/XAUUSD'),8000);const q=await qr.json();let events=[];try{const c1=await withTimeout(fetch('https://biquote.io/api/calendar/upcoming?importance=high'),8000).catch(function(){return null});const c2=await withTimeout(fetch('https://biquote.io/api/calendar?importance=high&countries=US'),8000).catch(function(){return null});const a=c1?await c1.json():[];const b=c2?await c2.json():[];events=[].concat(Array.isArray(a)?a:[],Array.isArray(b)?b:[])}catch(e){}q.mid=q.mid||q.bid;const s=initState(q);const h4=await ohlc('4h',80).catch(function(){return null});const h1=await ohlc('1h',120).catch(function(){return null});const m15=await ohlc('15m',120).catch(function(){return null});const m5=await ohlc('5m',80).catch(function(){return null});if(!loadHourPlan()||loadHourPlan().key!==hourKey())saveHourPlan(buildHourlyZones(q,s,h1,m15,m5));render(q,events,s,{h4:h4,h1:h1,m15:m15,m5:m5})}catch(e){$('chg').textContent='Price feed unavailable'}}
function boot(){try{if(window.TradingView)new TradingView.widget({autosize:true,symbol:'OANDA:XAUUSD',interval:'15',timezone:'Africa/Cairo',theme:'light',style:'1',locale:'en',enable_publishing:false,allow_symbol_change:false,container_id:'tvchart'})}catch(e){}$('reload').onclick=refresh;$('alertBtn').onclick=async function(){if(window.Notification&&Notification.permission!=='granted')await Notification.requestPermission()};refresh();setInterval(refresh,15000)}
if(document.readyState==='complete')boot();else window.addEventListener('load',boot);
